### ISSUE TITLE
How can I implement Grad-CAM on object detection??

### ISSUE THREAD

**Issue by SHAOSIHAN** [yizt/Grad-CAM.pytorch#5]
I find that almost code about Grad-CAM to be aimed classification model, so can it be implement on object detection model??

Recently I read some paper about attention, these papers use Grad-CAM to compare the performance improvement of object detection model, but I can find the code about visualization.

Can you give me some suggestion for modifying the code ?

Thanks!!!

**Comment by SHAOSIHAN** [comment]
I find that almost code about Grad-CAM to be aimed classification model, so can it be implement on object detection model??

Recently I read some paper about attention, these papers use Grad-CAM to compare the performance improvement of object detection model, but I can find the code about visualization.

Can you give me some suggestion for modifying the code ?

Thanks!!!

**Comment by yizt** [comment]
@SHAOSIHAN 您好，我会尽快实现目标检测部分，完成后通知您

**Comment by yizt** [comment]
@SHAOSIHAN 您好，已经更新目标检测部分，请更新工程！
